spring:
  config:
    import: optional:file:.env[.properties]

brevo:
  key: ${BREVO_API_KEY}
  url: ${BREVO_API_URL}

server:
  port: 8081

app:
  messaging:
    email:
      exchange: ${EXCHANGE_NAME}
      queue: ${QUEUE_NAME}
      routing-key: ${ROUTING_KEY}
      dlx: ${DLX_NAME}
      dlq: ${DLQ_NAME}